version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: valeo-neuro-erp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: valeo_neuro_erp
      POSTGRES_USER: valeo_dev
      POSTGRES_PASSWORD: valeo_dev_2024!
      POSTGRES_ROOT_PASSWORD: valeo_root_2024!
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./scripts/postgres.conf:/etc/postgresql/postgresql.conf:ro
    networks:
      - valeo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U valeo_dev -d valeo_neuro_erp"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: valeo-neuro-erp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/etc/redis/redis.conf:ro
    networks:
      - valeo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server /etc/redis/redis.conf

  # Keycloak Identity Provider
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: valeo-neuro-erp-keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123!
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/valeo_neuro_erp
      KC_DB_USERNAME: valeo_dev
      KC_DB_PASSWORD: valeo_dev_2024!
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 8080
      KC_HTTPS_PORT: 8443
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - valeo-network
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: localhost\r\nConnection: close\r\n\r\n' >&3;grep -q '200 OK' <&3"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    command: start-dev

  # pgAdmin Database Management
  pgadmin:
    image: dpage/pgadmin4:7
    container_name: valeo-neuro-erp-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@valeo-neuro-erp.com
      PGADMIN_DEFAULT_PASSWORD: admin123!
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - valeo-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # Redis Commander (Web UI for Redis)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: valeo-neuro-erp-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - valeo-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  valeo-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
