# VALEO-NeuroERP-3.0 Kubernetes Deployment Configuration
# Week 5: Containerization & Orchestration Implementation

apiVersion: apps/v1
kind: Deployment
metadata:
  name: valeo-neuroerp-3.0-deployment
  namespace: valeo-system
  labels:
    app: valeo-neuroerp
    version: "3.0"
    architecture: "clean-architecture"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: valeo-neuroerp
      component: api
  template:
    metadata:
      labels:
        app: valeo-neuroerp
        component: api
        version: "3.0"
        platform: "clean-architecture"
      annotations:
        valeo.io/owner: "neuroerp-team"
        valeo.io/architecture: "cost-effective-domain-driven"
    spec:
      serviceAccountName: valeo-neuroerp
      containers:
      - name: neuroerp-api
        image: valeo/neuroerp-3.0:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: SERVICE_PORT
          value: "3000"
        - name: CLEAN_ARCHITECTURE_ENABLED
          value: "true"
        - name: DOMAIN_SERVICES_ENABLED
          value: "crm,finance,inventory,analytics"
        envFrom:
        - configMapRef:
            name: valeo-neuroerp-config
        - secretRef:
            name: valeo-neuroerp-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/startup
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
        volumeMounts:
        - name: shared-config
          mountPath: /app/config
          readOnly: true
        - name: logs-volume
          mountPath: /app/logs
      - name: valeo-domains
        image: valeo/neuroerp-domains:latest
        ports:
        - containerPort: 3010
          name: crm-api
        - containerPort: 3011
          name: finance-api
        - containerPort: 3012
          name: inventory-api
        - containerPort: 3013
          name: analytics-api
        env:
        - name: DOMAIN_SERVICES_API
          value: "CRM,Finance,Inventory,Analytics"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: crm-api
          initialDelaySeconds: 15
          periodSeconds: 10
        
---

apiVersion: v1
kind: Service
metadata:
  name: valeo-neuroerp-service
  namespace: valeo-system
  labels:
    app: valeo-neuroerp
    version: "3.0"
spec:
  selector:
    app: valeo-neuroerp
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: crm-domain
    port: 3010
    targetPort: crm-api
    protocol: TCP
  - name: finance-domain
    port: 3011
    targetPort: finance-api
    protocol: TCP
  - name: inventory-domain
    port: 3012
    targetPort: inventory-api
    protocol: TCP
  - name: analytics-domain
    port: 3013
    targetPort: analytics-api
    protocol: TCP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: valeo-neuroerp-config
  namespace: valeo-system
data:
  API_VERSION: "v1"
  ENABLED_DOMAINS: "crm,finance,inventory,analytics"
  HEARTBEAT_INTERVAL: "30"
  LOG_LEVEL: "info"
---

