global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']
        labels:
          service: otel-collector

  - job_name: 'hr-domain'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3001']
        labels:
          service: hr-domain
